# Generated by Django 2.2.3 on 2020-01-04 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Influencer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('nickname', models.CharField(max_length=50, null=True)),
                ('level', models.CharField(max_length=50, null=True)),
                ('industry', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
