# Generated by Django 2.2.3 on 2020-01-08 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0003_auto_20200107_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtube',
            name='influencer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='youtube', to='influencers.Influencer'),
        ),
    ]
