# Generated by Django 2.2.3 on 2020-01-08 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0004_auto_20200107_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtube',
            name='youtube_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
