# Generated by Django 2.2.3 on 2020-01-08 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0002_twitter_youtube'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitter',
            name='influencer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twitter', to='influencers.Influencer'),
        ),
    ]
