# Generated by Django 2.2.3 on 2020-02-05 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0006_instagram'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_video_id', models.CharField(max_length=100)),
                ('youtube_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='youtube', to='influencers.Youtube')),
            ],
        ),
    ]
